### ISSUE TITLE
per-line report details in clover.xml

### ISSUE THREAD

**Issue by otrosien** [captin411/devel-cover-report-clover#5]
Hi, 
just asking if this project is still actively maintained as I have a feature request to include line or statement-based reporting in clover.xml. My goal is to read this into sonarqube to get project coverage reporting on a perl project. I would be willing to contribute.. :)

**Comment by captin411** [comment]
Hi there, I don't actively maintain this but if you have any modifications, I am more than willing to incorporate them and get a release out on CPAN.

**Comment by otrosien** [comment]
Just got back to developing on my sonarqube perl plugin, for which I prepared the first few releases. So, back to coverage reporting, and getting my head around Devel::Cover::Report::Clover. There's a first pull request, unrelated to this issue, but more for me to "get my hands dirty"...

**Comment by otrosien** [comment]
Amazing! Thanks alot, and even faster than anticipated!
